name: output_sample

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Add markdown to job summary
        shell: pwsh
        run: |
          $content = Get-Content markdown_sample.md -Raw
          $escapedContent = $content -replace "`n", "\\n"
          $escapedContent
          $escapedContent2 = $content -replace "`r`n", "\\n"
          $escapedContent2
          echo "output2=$escapedContent2" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": ${{ env.output2 }},
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
    
