name: output_sample

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - id: step1
        shell: pwsh
        run: |
          echo "output1='hello'" | Out-File -FilePath $env:GITHUB_ENV -Append
      - id: step2
        shell: pwsh
        run: |
          echo "output2='world'" | Out-File -FilePath $env:GITHUB_ENV -Append
    outputs:
      output1: ${{ env.output1 }}
      output2: ${{ env.output2 }}

  job2:
    needs: job1
    runs-on: windows-latest
    steps:
      - shell: pwsh
        run: |
          echo "${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}"
