name: output_sample

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Add markdown to job summary
        shell: pwsh
        run: |
          Get-Content markdown_sample.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
